sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=sanakalexbuilder
    - REGISTRY_PASS=sanakalexbuilderpassword
    - secret: "something long"

before_script:
  - docker pull distrlabproject/repository || true

script:
  - docker build --pull --cache-from distrlabproject/repository --tag distrlabproject/repository .
  - docker run distrlabproject/repository

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push distrlabproject/repository
  on:
    branch: master
