security:
  oauth2:
    client:
      clientId: user-service
      clientSecret: ${USER_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: user-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: iptstud
      port: 27017

server:
  context-path: /users
  port: 7000